name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_heroku:
    name: Deploy Docker image to Heroku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "notecraft"
          heroku_email: "bradleymorrisza@gmail.com"
          usedocker: true
